### ISSUE TITLE
极致版——旁路由设置dns有bug

### ISSUE THREAD

**Issue by zlfzy** [sirpdboy/luci-app-wizard#3]
我设置两个dns，dns1：223.5.5.5，dns2：223.6.6.6，应用后去查看接口配置，只有一个dns：223.6.6.6

**Comment by zxlhhyccc** [comment]
> 我设置两个dns，dns1：223.5.5.5，dns2：223.6.6.6，应用后去查看接口配置，只有一个dns：223.6.6.6

没问题，请更新到新版。。。。
